# CI/CD Workflow (non-production)
name: CI/CD

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write
  actions: read

jobs:
  # Lint
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: DavidAnson/markdownlint-cli2-action@v23
        with:
          config: .markdownlint-cli2.jsonc
